import React from 'react';
import { AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
import { HelpCircle } from 'lucide-react';
import { useAppStore } from '../../store/appStore';
import { useThemePalettes, tooltipStyle } from '../../theme';

interface ForecastDataPoint {
  day: string;
  value: number;
  type: 'historical' | 'predicted' | 'today';
}

// Static illustrative series — NOT a backend forecast. The chart is labelled
// as a demo projection so it can never be mistaken for live model output
// (issue 9 §21).
const FORECAST_SERIES: ForecastDataPoint[] = [
  { day: 'T-10d', value: 145, type: 'historical' },
  { day: 'T-8d', value: 152, type: 'historical' },
  { day: 'T-6d', value: 148, type: 'historical' },
  { day: 'T-4d', value: 160, type: 'historical' },
  { day: 'T-2d', value: 172, type: 'historical' },
  { day: 'Today', value: 185, type: 'today' },
  { day: 'P+2d', value: 191, type: 'predicted' },
  { day: 'P+4d', value: 198, type: 'predicted' },
  { day: 'P+6d', value: 215, type: 'predicted' },
  { day: 'P+8d', value: 202, type: 'predicted' },
  { day: 'P+10d', value: 210, type: 'predicted' },
  { day: 'P+12d', value: 226, type: 'predicted' },
  { day: 'P+14d', value: 238, type: 'predicted' },
];

export const ForecastChart: React.FC = () => {
  const theme = useAppStore((s) => s.theme);
  const palette = useThemePalettes();
  const c = palette.chart;
  const histColor = c.series[0];
  const todayColor = c.series[1];
  const predColor = c.series[5];

  return (
    <div className="sk-panel sk-panel-pad w-full h-[280px] relative overflow-hidden flex flex-col">
      <div className="flex justify-between items-start mb-2">
        <div>
          <span className="text-xs font-semibold text-[var(--text-muted)] flex items-center gap-1.5">
            <HelpCircle className="w-3.5 h-3.5" />
            Illustrative Outlook
          </span>
          <h4 className="sk-panel-title mt-0.5">14-Day Trend (Demo Projection)</h4>
        </div>
        <span
          title="This chart uses static sample data for illustration only. It is not generated by the validated forecast model and should not be used operationally."
          aria-label="Demo data: static sample series, not a live forecast"
          role="status"
          className="shrink-0 inline-flex items-center px-1.5 py-0.5 rounded border bg-amber-500/15 border-amber-500/40 text-amber-400 font-mono text-[8.5px] font-bold uppercase tracking-wide cursor-help"
        >
          Demo Data
        </span>
      </div>

      <div className="flex-1 w-full min-h-[200px] my-auto">
        <ResponsiveContainer width="100%" height="100%">
          <AreaChart data={FORECAST_SERIES} margin={{ top: 10, right: 10, left: -18, bottom: 0 }}>
            <defs>
              <linearGradient id="forecastGrad" x1="0" y1="0" x2="0" y2="1">
                <stop offset="5%" stopColor={predColor} stopOpacity={0.25} />
                <stop offset="95%" stopColor={predColor} stopOpacity={0} />
              </linearGradient>
            </defs>
            <XAxis dataKey="day" tickLine={false} axisLine={false} dy={6} tick={{ fill: c.axis, fontSize: 10.5 }} interval={1} />
            <YAxis tickLine={false} axisLine={false} dx={-4} tick={{ fill: c.axis, fontSize: 10.5 }} />
            <Tooltip
              contentStyle={tooltipStyle(theme)}
              formatter={(value: number) => [`${value} incidents`, 'Sample series']}
            />
            <Area
              type="monotone"
              dataKey="value"
              stroke={predColor}
              fillOpacity={1}
              fill="url(#forecastGrad)"
              strokeWidth={2}
              dot={(props: any) => {
                const { cx, cy, payload } = props;
                const fillColor =
                  payload.type === 'today' ? todayColor : payload.type === 'predicted' ? predColor : histColor;
                return <circle key={payload.day} cx={cx} cy={cy} r={3} fill={fillColor} stroke="none" />;
              }}
              activeDot={{ r: 5, strokeWidth: 2 }}
              name="Incidents"
            />
          </AreaChart>
        </ResponsiveContainer>
      </div>

      {/* Legend */}
      <div className="flex items-center flex-wrap gap-x-4 gap-y-1 text-[10px] font-mono text-[var(--text-muted)] pt-2 border-t border-[var(--border-muted)] mt-1">
        <span className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full" style={{ backgroundColor: histColor }} /> Historical</span>
        <span className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full" style={{ backgroundColor: todayColor }} /> Today</span>
        <span className="flex items-center gap-1.5"><span className="w-2 h-2 rounded-full" style={{ backgroundColor: predColor }} /> Sample projection</span>
        <span className="ml-auto flex items-center gap-1" title="Static sample series — no model confidence applies.">
          <HelpCircle className="w-3 h-3" />
          Not a live forecast
        </span>
      </div>
    </div>
  );
};

export default ForecastChart;
