"""Face-recognition routes — isolated DEMO enhancement (Issue #228).

All endpoints are behind the existing authentication/authorization and never
expose internal storage paths. When the feature is disabled a safe
"unavailable" state is returned; the rest of the application is unaffected.
"""
from __future__ import annotations

from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile
from fastapi.responses import Response
from sqlalchemy.orm import Session

from app.ai.face import repository as face_repo
from app.ai.face import zoho_adapter
from app.ai.face import synthetic as face_synthetic
from app.auth.dependencies import get_current_user
from app.auth.rbac import (
    ROLE_ADMIN,
    ROLE_CRIME_ANALYST,
    ROLE_FORENSIC,
    ROLE_INSPECTOR,
    ROLE_INVESTIGATOR,
    require_roles,
)
from app.core.config import settings
from app.database.postgres import get_db
from app.models.user import User
from app.schemas.face_recognition import (
    AIIdentifyResult,
    IdentityInfo,
    ProviderInfo,
    RecognizeResult,
    SampleImage,
)
from app.services import face_recognition_service
from app.services.face_recognition_service import feature_enabled

# Face identification of persons of interest is an operational/forensic action
# (least privilege): analysts, investigators, inspectors and forensic staff may
# run it. A pure VIEWER observing dashboards cannot scan faces. The demo gallery
# (synthetic images only) is served separately, unauthenticated.
router = APIRouter(
    prefix="/face-recognition",
    tags=["Face Recognition"],
    dependencies=[Depends(require_roles(ROLE_ADMIN, ROLE_CRIME_ANALYST, ROLE_INVESTIGATOR, ROLE_INSPECTOR, ROLE_FORENSIC))],
)


def _ensure_enabled() -> None:
    if not feature_enabled():
        raise HTTPException(status_code=503, detail="Face recognition is disabled on this deployment.")


def _serve_sample(ref: str) -> Response:
    data = face_recognition_service.sample_bytes(ref)
    if data is None:
        raise HTTPException(status_code=404, detail="Sample image not found.")
    return Response(content=data, media_type="image/png")


@router.post("/recognize", response_model=RecognizeResult)
async def recognize(
    file: UploadFile = File(...),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Analyze an uploaded image, detect faces, and compare against the DEMO dataset."""
    _ensure_enabled()
    try:
        face_repo.ensure_seeded(db)
    except face_repo.FaceRepositoryError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    # Release the pooled DB connection before the heavy detection/analysis work
    # (Zoho network call, image decoding, embedding math). The recognition
    # pipeline itself is DB-independent — matching runs off the on-disk DEMO
    # dataset — so holding a pool slot here would starve other requests.
    db.close()
    try:
        return face_recognition_service.recognize(file)
    except face_recognition_service.FaceProcessingError as exc:
        raise HTTPException(status_code=exc.status, detail=exc.message) from None


@router.post("/test-sample", response_model=RecognizeResult)
async def recognize_sample(
    image_ref: str,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Run recognition directly on a demo sample image (jury quick-test)."""
    _ensure_enabled()
    try:
        face_repo.ensure_seeded(db)
    except face_repo.FaceRepositoryError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    data = face_recognition_service.sample_bytes(image_ref)
    if data is None:
        raise HTTPException(status_code=404, detail="Sample image not found.")
    db.close()
    result = face_recognition_service.recognize_bytes(data)
    result["queried_sample"] = image_ref
    return result


@router.post("/ai/identify", response_model=AIIdentifyResult)
async def ai_identify(
    file: UploadFile = File(...),
    question: str | None = Form(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Analyze an uploaded face and answer an optional question about it.

    The answer is generated by deterministic rules over the recognition result —
    it is NOT a hosted LLM, and it never fabricates a positive identity beyond
    what the DEMO dataset supports.
    """
    _ensure_enabled()
    try:
        face_repo.ensure_seeded(db)
    except face_repo.FaceRepositoryError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    db.close()
    try:
        result = face_recognition_service.recognize(file)
    except face_recognition_service.FaceProcessingError as exc:
        raise HTTPException(status_code=exc.status, detail=exc.message) from None
    return AIIdentifyResult(
        answer=face_recognition_service.ai_answer(result, question),
        engine="rule-based",
        recognition=RecognizeResult.model_validate(result),
        question=question,
    )


@router.get("/demo-info")
def demo_info(current_user: User = Depends(get_current_user)):
    """Public demo dataset metadata used by the frontend quick-test UI."""
    _ensure_enabled()
    identities = []
    for ident in face_synthetic.IDENTITIES:
        identities.append(
            {
                "id": ident.demo_id,
                "name": ident.display_name,
                "variations": face_synthetic.VARIATIONS,
                "prompt": ident.hair_style,
            }
        )
    return {"identities": identities}


@router.get("/identities", response_model=list[IdentityInfo])
def identities(db: Session = Depends(get_db), current_user: User = Depends(get_current_user)):
    """List DEMO identities (metadata only)."""
    _ensure_enabled()
    try:
        face_repo.ensure_seeded(db)
        return face_repo.list_identities(db)
    except face_repo.FaceRepositoryError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc


@router.get("/samples", response_model=list[SampleImage])
def samples(db: Session = Depends(get_db), current_user: User = Depends(get_current_user)):
    """List the demo gallery image references for the jury testing UI."""
    _ensure_enabled()
    try:
        face_repo.ensure_seeded(db)
        return face_repo.list_sample_images(db)
    except face_repo.FaceRepositoryError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc


@router.get("/sample-image/{image_ref:path}", response_class=Response)
def sample_image(image_ref: str, current_user: User = Depends(get_current_user)):
    """Serve a demo sample image by logical reference (internal path hidden)."""
    _ensure_enabled()
    return _serve_sample(image_ref)


# Unauthenticated endpoint for <img> tags in the gallery (synthetic demo images only).
_public_router = APIRouter(
    prefix="/face-recognition",
    tags=["Face Recognition (Demo)"],
)


@_public_router.get("/gallery/{image_ref:path}", response_class=Response)
def gallery_image(image_ref: str):
    """Public endpoint to serve demo sample images (synthetic, non-sensitive)."""
    _ensure_enabled()
    return _serve_sample(image_ref)


@router.get("/provider", response_model=ProviderInfo)
def provider(current_user: User = Depends(get_current_user)):
    """Report which face-analysis provider is active and its capabilities."""
    zoho = zoho_adapter.get_zoho_adapter().describe()
    from app.ai.face.synthetic import IDENTITIES

    return ProviderInfo(
        main={
            "provider": face_recognition_service._provider_name(),
            "enabled": feature_enabled(),
            "identities": len(IDENTITIES),
        },
        zoho=zoho,
        threshold=float(settings.FACE_MATCH_THRESHOLD or 0.6),
        enabled=feature_enabled(),
    )


@router.get("/status")
def status(current_user: User = Depends(get_current_user)):
    """Simple feature availability flag (used by the AI layer and UI)."""
    return {
        "enabled": feature_enabled(),
        "provider": face_recognition_service._provider_name(),
        "threshold": float(settings.FACE_MATCH_THRESHOLD or 0.6),
    }
