"""Pydantic schemas for the isolated face-recognition feature (Issue #228)."""
from typing import Any

from pydantic import BaseModel, Field


class MatchedPerson(BaseModel):
    id: str = Field(..., description="DEMO identity id, e.g. DEMO-001")
    name: str = Field(..., description="Display name")
    dataset_type: str = Field("DEMO", description="Always DEMO for the prototype dataset")


class ScanFaceInfo(BaseModel):
    """Per-face detected information returned to the client."""

    index: int = Field(..., description="0-based face index in the image")
    bbox: dict[str, float] = Field(default_factory=dict, description="Normalized bounding box")
    gender: str | None = None
    age: str | None = None
    emotion: str | None = None


class FaceAnalysis(BaseModel):
    faces: int = 0
    age: str | None = None
    gender: str | None = None
    emotion: str | None = None


class RecognizeResult(BaseModel):
    """Structured recognition result for one uploaded query image."""

    status: str = Field(
        ...,
        description="match | no_match | no_face | no_reference | disabled",
    )
    faces_detected: int = 0
    match_found: bool = False
    matched_person: MatchedPerson | None = None
    confidence: float | None = None
    best_score: float | None = None
    message: str | None = None
    analysis: FaceAnalysis | None = None
    analysis_source: str | None = Field(None, description="zoho | local")
    threshold: float | None = None


class IdentityInfo(BaseModel):
    """DEMO identity metadata (no internal paths exposed)."""

    id: str
    name: str
    dataset_type: str
    image_count: int
    created_at: str | None = None


class SampleImage(BaseModel):
    """A demo gallery image reference (logical, internal paths never exposed)."""

    id: str
    name: str
    image_ref: str
    variation: str


class ProviderInfo(BaseModel):
    """Capability summary for the configured providers (non-sensitive)."""

    main: dict[str, Any]
    zoho: dict[str, Any]
    threshold: float
    enabled: bool


class AIIdentifyResult(BaseModel):
    """Natural-language answer + structured recognition for the AI identify flow."""

    answer: str = Field(..., description="Honest natural-language explanation of the result")
    engine: str = Field(
        "rule-based",
        description="Recognition answer is generated by deterministic rules, not a hosted LLM",
    )
    recognition: RecognizeResult = Field(..., description="Structured recognition result")
    question: str | None = None
