"""Central alert policy — single authoritative source for all thresholds, detection
rules, severity definitions, provenance handling, and confidence classification.

Issue #10 P2: Formalize Red-Zone, Anomaly, and Incident-Priority Thresholds
in a Single Policy.

Every alert generated by the system must trace its thresholds and methodology
back to this module.  Duplicate threshold values elsewhere are prohibited.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


# ---------------------------------------------------------------------------
# Policy version
# ---------------------------------------------------------------------------

ALERT_POLICY_VERSION = "v1"


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class AlertType(str, Enum):
    """All supported alert types."""
    RED_ZONE_SPIKE = "RED_ZONE_SPIKE"
    CRIME_SPIKE = "CRIME_SPIKE"
    ANOMALY = "ANOMALY"
    INCIDENT_PRIORITY = "INCIDENT_PRIORITY"


class AlertSeverity(str, Enum):
    """Standardised severity levels (matches existing Notification.severity)."""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFORMATIONAL = "informational"


class AlertStatus(str, Enum):
    """Alert lifecycle states (maps to existing Notification.status)."""
    NEW = "unread"
    ACKNOWLEDGED = "acknowledged"
    UNDER_REVIEW = "under_review"
    ESCALATED = "escalated"
    RESOLVED = "resolved"
    DISMISSED = "dismissed"


class Confidence(str, Enum):
    """Meaningful confidence classification — never fabricated percentages."""
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class Provenance(str, Enum):
    """Dataset provenance tags (see ImportProvenanceMixin)."""
    LIVE = "LIVE"
    DEMO = "DEMO"
    MIXED = "MIXED"
    UNKNOWN = "UNKNOWN"


class BaselineStatus(str, Enum):
    """Whether the historical baseline is sufficient for reliable detection."""
    SUFFICIENT = "SUFFICIENT"
    INSUFFICIENT_BASELINE = "INSUFFICIENT_BASELINE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


# ---------------------------------------------------------------------------
# Red-Zone / Crime-Spike thresholds
#
# Rationale (existing system: redzone_service.py):
#   - Current window: last 30 days
#   - Baseline window: prior 90 days (days 31-120 ago)
#   - Minimum current incidents: 3 (default, configurable)
#   - Spike ratio threshold: 1.5× (configurable)
#   - Critical severity: zero baseline AND count >= 5, OR ratio >= 2.5
#   - Minimum baseline observations for reliable detection: 1
#     (below this, mark INSUFFICIENT_BASELINE)
# ---------------------------------------------------------------------------

class RedZoneThresholds:
    """Red-zone and crime-spike detection thresholds."""

    # --- Windows ---
    CURRENT_WINDOW_DAYS: int = 30
    BASELINE_WINDOW_DAYS: int = 90

    # --- Minimum evidence ---
    MIN_CURRENT_COUNT: int = 3
    MIN_BASELINE_OBSERVATIONS: int = 1  # below this → INSUFFICIENT_BASELINE

    # --- Spike ratio ---
    RATIO_THRESHOLD: float = 1.5

    # --- Severity rules ---
    CRITICAL_RATIO: float = 2.5
    CRITICAL_ZERO_BASELINE_COUNT: int = 5

    # --- Anomaly (statistical z-score) threshold for red-zone anomaly flag ---
    ANOMALY_Z_THRESHOLD: float = 2.0


# ---------------------------------------------------------------------------
# Anomaly detection thresholds (statistical, non-ML)
#
# For the red-zone service's built-in anomaly evaluation (z-score based).
# The AI/ML anomaly model (anomaly.py) uses its own threshold stored in the
# model artifact and is NOT duplicated here.
# ---------------------------------------------------------------------------

class AnomalyThresholds:
    """Statistical anomaly detection thresholds for aggregate analytics."""

    # Minimum observations before z-score is meaningful
    MIN_OBSERVATIONS: int = 5

    # Z-score beyond which a value is considered anomalous
    Z_SCORE_THRESHOLD: float = 2.0


# ---------------------------------------------------------------------------
# Incident priority factors
#
# Only factors that actually exist in the SAKSHA data model are listed.
# These map to columns on CrimeCase, Criminal, FIR, and Location.
# ---------------------------------------------------------------------------

# Severity mapping from CrimeCategory.severity → priority weight
CATEGORY_SEVERITY_WEIGHTS: dict[str, float] = {
    "high": 1.0,
    "medium": 0.5,
    "low": 0.2,
}

# Priority levels for individual incidents (matches CrimeCase.priority)
PRIORITY_LEVELS = ["critical", "high", "medium", "low"]

# Thresholds for incident priority classification based on category severity,
# open-case backlog, and linked-criminal count.
INCIDENT_PRIORITY_THRESHOLDS: dict[str, Any] = {
    # Incident becomes CRITICAL if all three conditions met:
    "critical_all": {
        "category_severity": "high",
        "min_open_fir_count": 3,
        "min_linked_criminals": 2,
    },
    # Incident becomes HIGH if category severity is high OR any two:
    "high_any": {
        "category_severity": "high",
        "min_open_fir_count": 2,
        "min_linked_criminals": 1,
    },
    # MEDIUM: category severity medium or at least one factor
    "medium_any": {
        "category_severity": "medium",
        "min_open_fir_count": 1,
    },
}


# ---------------------------------------------------------------------------
# District ranking
#
# Metric: raw incident count in the current window.
# No population normalisation (no reliable per-district population data).
# No severity weighting (keeps ranking transparent and reproducible).
# ---------------------------------------------------------------------------

class DistrictRanking:
    """How districts are ranked."""
    METRIC: str = "incident_count"
    WINDOW_DAYS: int = 30
    NORMALISED: bool = False
    POPULATION_ADJUSTED: bool = False
    MIN_EVIDENCE: int = 1


# ---------------------------------------------------------------------------
# Crime-category ranking
#
# Metric: total incidents in the current window, descending.
# Secondary sort: change percentage vs prior window.
# ---------------------------------------------------------------------------

class CategoryRanking:
    """How crime categories are ranked."""
    METRIC: str = "incident_count"
    WINDOW_DAYS: int = 30
    SECONDARY_METRIC: str = "change_percentage"
    MIN_EVIDENCE: int = 1


# ---------------------------------------------------------------------------
# Minimum evidence requirements
# ---------------------------------------------------------------------------

class EvidenceRequirements:
    """Minimum evidence for alert generation."""
    MIN_INCIDENT_COUNT: int = 3
    MIN_HISTORICAL_OBSERVATIONS: int = 1
    MIN_SUPPORTING_RECORDS: int = 1


# ---------------------------------------------------------------------------
# Deduplication
#
# Key = (district, category, alert_type, policy_version, time_window_label)
# An existing unread notification with the same resource_id suppresses
# duplicate creation (already implemented in notify_red_zones).
# ---------------------------------------------------------------------------

DEDUP_WINDOW_MINUTES: int = 60


# ---------------------------------------------------------------------------
# Alert explanation template
# ---------------------------------------------------------------------------

def build_alert_explanation(
    *,
    alert_type: AlertType,
    district: str,
    category: str,
    current_count: int,
    baseline_count: float,
    spike_ratio: float,
    policy_version: str = ALERT_POLICY_VERSION,
) -> str:
    """Return a human-readable explanation for a generated alert."""
    change_pct = (
        round(((current_count - baseline_count) / max(baseline_count, 0.5)) * 100, 1)
        if baseline_count > 0
        else 100.0
    )
    sign = "+" if change_pct >= 0 else ""
    return (
        f"{alert_type.value}: {category} in {district}\n"
        f"Current period: {current_count} incidents\n"
        f"Historical baseline: {baseline_count} incidents\n"
        f"Change: {sign}{change_pct}%\n"
        f"Spike ratio: {spike_ratio}×\n"
        f"Policy: Alert Policy {policy_version}"
    )


# ---------------------------------------------------------------------------
# Admin inspection helper
# ---------------------------------------------------------------------------

def get_current_policy() -> dict[str, Any]:
    """Return the full current policy for admin inspection."""
    return {
        "policy_version": ALERT_POLICY_VERSION,
        "red_zone": {
            "current_window_days": RedZoneThresholds.CURRENT_WINDOW_DAYS,
            "baseline_window_days": RedZoneThresholds.BASELINE_WINDOW_DAYS,
            "min_current_count": RedZoneThresholds.MIN_CURRENT_COUNT,
            "min_baseline_observations": RedZoneThresholds.MIN_BASELINE_OBSERVATIONS,
            "ratio_threshold": RedZoneThresholds.RATIO_THRESHOLD,
            "critical_ratio": RedZoneThresholds.CRITICAL_RATIO,
            "critical_zero_baseline_count": RedZoneThresholds.CRITICAL_ZERO_BASELINE_COUNT,
        },
        "anomaly": {
            "min_observations": AnomalyThresholds.MIN_OBSERVATIONS,
            "z_score_threshold": AnomalyThresholds.Z_SCORE_THRESHOLD,
        },
        "incident_priority": {
            "levels": PRIORITY_LEVELS,
            "thresholds": INCIDENT_PRIORITY_THRESHOLDS,
        },
        "district_ranking": {
            "metric": DistrictRanking.METRIC,
            "window_days": DistrictRanking.WINDOW_DAYS,
            "normalised": DistrictRanking.NORMALISED,
            "population_adjusted": DistrictRanking.POPULATION_ADJUSTED,
            "min_evidence": DistrictRanking.MIN_EVIDENCE,
        },
        "category_ranking": {
            "metric": CategoryRanking.METRIC,
            "window_days": CategoryRanking.WINDOW_DAYS,
            "secondary_metric": CategoryRanking.SECONDARY_METRIC,
            "min_evidence": CategoryRanking.MIN_EVIDENCE,
        },
        "evidence_requirements": {
            "min_incident_count": EvidenceRequirements.MIN_INCIDENT_COUNT,
            "min_historical_observations": EvidenceRequirements.MIN_HISTORICAL_OBSERVATIONS,
            "min_supporting_records": EvidenceRequirements.MIN_SUPPORTING_RECORDS,
        },
        "dedup_window_minutes": DEDUP_WINDOW_MINUTES,
    }
